/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lipstick-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>

      <group position={[-1.43, 0, 3.86]} rotation={[2 * Math.PI / 2, 0, -Math.PI / 3]} >
        <group position={[-3.01, 0.47, 0]} rotation={[0, 0, -1.56]}>
          <mesh geometry={nodes.Mesh_3.geometry} material={materials.Gold_Gloss} />
        </group>
        <group position={[-3.01, 0.47, 0]} rotation={[0, 0, -1.56]}>
          <mesh geometry={nodes.Mesh_0.geometry} material={nodes.Mesh_0.material} />
        </group>
        <group position={[-0.82, 0.55, -0.72]} rotation={[0.02, 0.38, -1.62]}>
          <mesh
            geometry={nodes.Mesh_1.geometry}
            material={nodes.Mesh_1.material}
            material-emissive={props.shadowColor}
            position={[0.03, -1.19, -0.39]}
          />
        </group>
        <group position={[-3.01, 0.47, 0]} rotation={[0, 0, -1.56]}>
          <mesh geometry={nodes.Mesh_2.geometry} material={materials['Gold_Gloss.001']} />
        </group>
        <group position={[-1.54, 0.48, 0]} rotation={[-0.71, 0, -1.56]}>
          <mesh material={materials.Paint} geometry={nodes.Mesh_4.geometry} />
        </group>
      </group>

    </group>
  )
}

useGLTF.preload('/lipstick-transformed.glb')

