/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/question-block-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.pasted__VRayMtl1SG}
        position={[-0.11, -0.13, 0.38]}
        material-emissive={props.shadowColor}
      />
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.pasted__VRayMtl5SG}
        position={[0, 0, 0.13]}
        material-emissive={props.shadowColor}
      />
    </group>
  )
}

useGLTF.preload('/question-block-transformed.glb')
