/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/stopwatch-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh material-emissive={props.shadowColor} geometry={nodes.defaultMaterial001.geometry} material={materials.material_9} />
          <mesh material-emissive={props.shadowColor} geometry={nodes.defaultMaterial002.geometry} material={materials.material_8} />
          <mesh material-emissive={props.shadowColor} geometry={nodes.defaultMaterial003.geometry} material={materials.material} />
          <mesh material-emissive={props.shadowColor} geometry={nodes.defaultMaterial004.geometry} material={materials.material_6} />
          <mesh geometry={nodes.defaultMaterial009.geometry} material={materials.material_1} />
          <mesh material-emissive={props.shadowColor} geometry={nodes.defaultMaterial007.geometry} material={materials.material_3} />
          <mesh material-emissive={props.shadowColor} geometry={nodes.defaultMaterial008.geometry} material={materials.material_2} />
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material_10} />
          <mesh geometry={nodes.defaultMaterial006.geometry} material={materials.material_4} />
          <mesh geometry={nodes.defaultMaterial005.geometry} material={materials.material_5} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stopwatch-transformed.glb')

