/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/untitled-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_0.geometry}
        material={materials.wire_154185229}
        rotation={[1.48, 0.12, 1.58]}
        scale={0.1}
      />
    </group>
  )
}

useGLTF.preload('/untitled-transformed.glb')
